#!/usr/bin/env python3
"""Build references.bib from the \\bibitem entries in the main document.

The Word source carried an IEEE-style numbered reference list, which was
converted into a literal ``thebibliography``. This script parses those entries
into BibTeX so the document can use BibTeX instead, keeping the keys (ref1,
ref2, ...) that the \\cite commands already use.

Each entry is written as @misc with the parts that can be identified
(author, title, year) and the remainder in ``howpublished``, so the printed
reference stays close to the original wording.

Usage:
    python3 tools/bibitems2bib.py main-thematic-traditional.tex -o references.bib
"""
import argparse
import re

BIBITEM_RE = re.compile(r"\\bibitem\{(ref\d+)\}\s*(.*?)(?=\\bibitem\{|\\end\{thebibliography\})",
                        re.S)
# ``Title,'' or ``Title''  (TeX quotes produced by the converter)
TITLE_RE = re.compile(r"``(.+?),?''", re.S)
YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")


def clean(text):
    return re.sub(r"\s+", " ", text).strip().strip(",.").strip()


# A personal name in this list starts with initials: "M. Hirano", "M. E. Ahmed".
PERSON_RE = re.compile(r"^(?:[A-Z]\.\s*)+[A-Z]")


def format_authors(raw):
    """BibTeX wants ``A and B and C``; the source uses ``A, B, and C``.

    Organisations ("CISA and FBI", "IBM Security and Ponemon Institute") must
    not be split on "and", so they are kept whole and brace-protected.
    """
    if not raw:
        return ""
    parts = [p for p in re.split(r",\s*(?:and\s+)?|\s+and\s+", raw) if p.strip()]
    if parts and all(PERSON_RE.match(p.strip()) for p in parts):
        return " and ".join(p.strip() for p in parts)
    return "{%s}" % raw  # organisation: one name, kept verbatim


def parse(body):
    """Split one reference into author / title / rest / year."""
    body = re.sub(r"\s+", " ", body).strip()
    m = TITLE_RE.search(body)
    if m:
        author = clean(body[:m.start()])
        title = clean(m.group(1))
        rest = clean(body[m.end():])
    else:
        # No quoted title: take the text up to the first period as the title.
        parts = body.split(". ", 1)
        first = parts[0]
        # "IBM Security and Ponemon Institute, Cost of a Data Breach Report 2025"
        if "," in first:
            author, title = first.split(",", 1)
            author, title = clean(author), clean(title)
        else:
            author, title = "", clean(first)
        rest = clean(parts[1]) if len(parts) > 1 else ""
    ym = list(YEAR_RE.finditer(body))
    year = ym[-1].group(0) if ym else ""
    # The year usually also closes the venue text ("NeurIPS 2025",
    # "Advisory AA23-039A, Feb. 2023"). Drop it there so the printed reference
    # does not end with the year twice.
    if year and rest.endswith(year):
        rest = clean(re.sub(r"[,\s]*" + year + r"$", "", rest))
    return author, title, rest, year


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source", help="the .tex file holding the thebibliography block")
    ap.add_argument("-o", "--output", default="references.bib")
    args = ap.parse_args()

    text = open(args.source, encoding="utf-8").read()
    entries = BIBITEM_RE.findall(text)
    if not entries:
        raise SystemExit("no \\bibitem entries found in " + args.source)

    out = [
        "% Generated by tools/bibitems2bib.py from the numbered reference list",
        "% carried over from the Word source. Keys match the \\cite commands in",
        "% the document (ref1, ref2, ...), and the order of the keys is the",
        "% numbering used in the original manuscript.",
        "",
    ]
    for key, body in entries:
        author, title, rest, year = parse(body)
        out.append("@misc{%s," % key)
        if author:
            out.append("  author       = {%s}," % format_authors(author))
        # Double braces keep the manuscript's capitalisation: bibliography
        # styles otherwise lower-case titles.
        out.append("  title        = {{%s}}," % title)
        if rest:
            out.append("  howpublished = {%s}," % rest)
        if year:
            out.append("  year         = {%s}," % year)
        out.append("}")
        out.append("")

    open(args.output, "w", encoding="utf-8").write("\n".join(out))
    print("Wrote %s (%d entries)" % (args.output, len(entries)))


if __name__ == "__main__":
    main()
